apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labesl:
    app: wordpress
spec:
  prots:
    - port: 80
      nodePort: 31004
  selector:
    app: wordpress
    tier: frontend
  type: NodePort

