apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels: 
    app: myapp
    tier: frontend
spec:
  template:
    metadata:
      name: myapp
      labels: 
        name: myapp
        tier: frontend
    spec:
      containers:
        - name: nginx-app
          image: nginx
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
