apiVersion: v1
kind: ReplicationController
metadata:
  name: appreplica
  labels:
    app: appreplica
    type: frontend
spec:
  template:
    metadata: 
      name: mypod
      labels:
        app: mypod
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  

