apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: my-pod
      labels: 
        app: mynginx
        type: server
    spec:
      containers:
      - name: my-nginx-server
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: mynginx
